import Link from 'next/link';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import CalculatorCard from '@/components/calculators/CalculatorCard';
import { calculators } from '@/data/calculators';
export const metadata={title:'Property Finance Calculators | Your Home',description:'Calculate EMI, true property cost, affordability, rental ROI, risk and buy versus rent with Your Home.'};
export default function CalculatorsPage(){return <><Navbar/><main><section className="border-b border-ink/10 bg-[#eef1ea]"><div className="mx-auto max-w-[1360px] px-5 py-14 lg:px-10 lg:py-16"><p className="eyebrow">PROPERTY FINANCE TOOLS</p><h1 className="mt-4 max-w-3xl font-serif text-5xl leading-[.96] tracking-[-.05em] md:text-7xl">Understand the Numbers Before You Buy.</h1><p className="mt-6 max-w-2xl leading-7 text-ink/60">Calculate EMI, true ownership cost, affordability, rental returns and risk before making a property decision.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-dark" href="/calculators/affordability">Start with affordability <ArrowUpRight size={16}/></Link><Link className="btn-outline" href="/smart-recommendation">Get smart recommendation</Link></div></div></section><section className="mx-auto max-w-[1360px] px-5 py-16 lg:px-10"><div className="mb-9"><p className="eyebrow">SIX TOOLS, ONE CLEARER DECISION</p><h2 className="section-title mt-3">Build your financial picture</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{calculators.map(tool=><CalculatorCard key={tool.slug} tool={tool}/>)}</div></section><section className="bg-[#15352c] px-5 py-16 text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="eyebrow !text-[#a6cbbd]">OUR INNOVATION</p><div className="mt-4 grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="font-serif text-4xl leading-[.95] md:text-5xl">Smart Recommendation</h2><p className="mt-5 leading-7 text-white/60">Combine your finances with property data to understand whether buying now makes sense for you.</p><Link href="/smart-recommendation" className="btn-light mt-7">Get my smart recommendation <ArrowUpRight size={16}/></Link></div><div className="grid gap-3 md:grid-cols-4"><Flow title="Your finances" items="Income · Expenses · EMI · Savings"/><ArrowDown className="m-auto hidden text-[#a6cbbd] md:block"/><Flow title="We analyze" items="EMI · True cost · Affordability · Risk"/><ArrowDown className="m-auto hidden text-[#a6cbbd] md:block"/><Flow title="Your decision" items="BUY · WAIT · RENT · AVOID"/></div></div></div></section></main><Footer/></>}
function Flow({title,items}){return <div className="rounded-2xl border border-white/15 bg-white/[.05] p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#a6cbbd]">{title}</p><p className="mt-4 text-sm leading-6 text-white/70">{items}</p></div>}
