import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const source=await readFile(new URL('../lib/calculators/rentalRoi.js',import.meta.url),'utf8');
const {calculateRentalROI,calculateEMI}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const base={propertyPrice:8000000,trueAcquisitionCost:8600000,monthlyRent:35000,vacancyRate:5,propertyTax:90000,financed:false,holdingYears:5};
const cash=calculateRentalROI(base);
assert.equal(cash.grossAnnualRent,420000);
assert.equal(cash.vacancyLoss,21000);
assert.equal(cash.effectiveRentalIncome,399000);
assert.equal(cash.noi,309000);
assert.ok(Math.abs(cash.grossRentalYield-4.88372093)<1e-6);
assert.ok(Math.abs(cash.netRentalYield-3.59302325)<1e-6);
assert.ok(Math.abs(calculateEMI(5000000,8.5,20)-43391.15)<1);
const financed=calculateRentalROI({...base,financed:true,loanAmount:5000000,downPayment:3000000,interestRate:8.5,tenureYears:20});
assert.ok(financed.monthlyCashFlow<0);
const vacancy=[0,5,10,20].map(v=>calculateRentalROI({...base,vacancyRate:v}));
for(let i=1;i<vacancy.length;i++) assert.ok(vacancy[i].noi<vacancy[i-1].noi&&vacancy[i].netRentalYield<vacancy[i-1].netRentalYield&&vacancy[i].annualCashFlow<vacancy[i-1].annualCashFlow);
const rents=[25000,35000,50000,75000].map(monthlyRent=>calculateRentalROI({...base,monthlyRent}));
for(let i=1;i<rents.length;i++) assert.ok(rents[i].grossAnnualIncome>rents[i-1].grossAnnualIncome&&rents[i].noi>rents[i-1].noi&&rents[i].netRentalYield>rents[i-1].netRentalYield);
const costs=[5000000,8000000,10000000,20000000].map(propertyPrice=>calculateRentalROI({...base,trueAcquisitionCost:0,propertyPrice}));
for(let i=1;i<costs.length;i++) assert.ok(costs[i].netRentalYield<costs[i-1].netRentalYield);
const loans=[0,2000000,4000000,6000000].map(loanAmount=>calculateRentalROI({...base,financed:true,loanAmount,downPayment:3000000,interestRate:8.5,tenureYears:20}));
for(let i=1;i<loans.length;i++) assert.ok(loans[i].monthlyEMI>loans[i-1].monthlyEMI&&loans[i].annualCashFlow<loans[i-1].annualCashFlow);
const zero=calculateRentalROI({propertyPrice:0,monthlyRent:0,loanAmount:0,holdingYears:5});
for(const key of ['grossRentalYield','netRentalYield','noi','annualCashFlow']) assert.ok(Number.isFinite(zero[key])&&zero[key]===0);
const flat=calculateRentalROI({...base,appreciationRate:0,rentGrowthRate:0,holdingYears:5});
assert.equal(flat.projection[4].propertyValue,flat.acquisitionCost);
assert.equal(flat.projection[4].annualRent,flat.grossAnnualIncome);
assert.equal(flat.projection[4].loanBalance,0);
console.log('Rental ROI deterministic and invariant tests passed.');
