import { calculateAffordability, calculateRentalRoi, calculateRisk, calculateTrueCost, calculateBuyVsRent } from '@/lib/calculators';

export function getRecommendation({ buyer, property, loan }) {
  const affordability=calculateAffordability({...buyer,propertyPrice:property.price,downPayment:loan.downPayment,interestRate:loan.interestRate,tenureYears:loan.tenureYears});
  const trueCost=calculateTrueCost({propertyPrice:property.price,downPayment:loan.downPayment,interestRate:loan.interestRate,tenureYears:loan.tenureYears,stampDuty:property.price*.07,registration:property.price*.01,maintenanceDeposit:property.maintenance});
  const roi=calculateRentalRoi({propertyPrice:property.price,monthlyRent:property.expectedRent,annualMaintenance:property.maintenance*12,vacancyPercent:5});
  const risk=calculateRisk({...affordability,emergencyFund:buyer.emergencyFund,possessionStatus:property.possessionStatus,netYield:roi.netYield});
  const buyVsRent=calculateBuyVsRent({propertyPrice:property.price,downPayment:loan.downPayment,interestRate:loan.interestRate,tenureYears:loan.tenureYears,registration:property.price*.08,annualMaintenance:property.maintenance*12,monthlyRent:buyer.currentRent,years:5});
  let decision='BUY'; if(affordability.cashRemaining<0||affordability.emiBurden>65||risk.level==='High Risk') decision='AVOID'; else if(affordability.emiBurden>52||affordability.savingsRemaining<buyer.emergencyFund) decision=buyer.currentRent>0&&buyVsRent.monthlyDifference>buyer.currentRent?'RENT':'WAIT'; else if(affordability.status==='Stretch'||risk.level==='Moderate Risk') decision='WAIT';
  const positives=[],warnings=[...risk.flags]; if(affordability.emiBurden<=35) positives.push('Your total EMI burden is within the recommended comfort range.'); if(affordability.cashRemaining>0) positives.push('Your expected monthly cash flow remains positive after the new EMI.'); if(affordability.savingsRemaining>=buyer.emergencyFund) positives.push('Your expected savings remain above your preferred emergency reserve.'); if(roi.netYield>=3) positives.push('The estimated rental yield provides some income potential.'); if(!positives.length) positives.push('Use the what-if controls to test a lower loan amount or higher down payment.');
  const explanation={BUY:'Based on the information provided, this property appears reasonably aligned with your current finances.',WAIT:'The property may suit your needs, but buying now could put noticeable pressure on your finances.',RENT:'Renting may currently provide greater financial flexibility while you strengthen savings and reduce monthly debt.',AVOID:'The combination of affordability pressure and available property risk factors makes this property unsuitable under your current assumptions.'}[decision];
  return { decision, explanation, positives, warnings, metrics:{...affordability,trueCost:trueCost.trueCost,rentalYield:roi.netYield,riskLevel:risk.level,buyVsRent} };
}
