'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import * as Icons from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import PropertySearch from '@/components/PropertySearch';
import PropertyCard from '@/components/PropertyCard';
import RecommendationPreview from '@/components/RecommendationPreview';
import { getHomeData } from '@/services/home';
import { cities, tools } from '@/data/home';

export default function HomePage(){
  const [city,setCity]=useState(cities[0]);
  const {data,isLoading,isError,refetch}=useQuery({queryKey:['home'],queryFn:getHomeData});
  const visible=data?.featuredProperties.filter(p=>p.city===city).slice(0,3)||[];
  return <><Navbar/><main>
    <section className="hero"><div className="mx-auto max-w-[1440px] px-5 pb-16 pt-14 lg:px-10 lg:pb-24 lg:pt-20"><div className="mb-10 max-w-4xl"><p className="eyebrow">REAL ESTATE, MADE CLEAR</p><h1 className="mt-5 font-serif text-[clamp(3.15rem,7vw,6.8rem)] leading-[.91] tracking-[-.055em]">Find the right property.<br/><span className="text-green">Make the right decision.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-ink/60 md:text-lg">Explore properties in Gurugram & Ghaziabad and understand what they really mean for your finances.</p></div><PropertySearch/><p className="mt-4 text-sm text-ink/50">Are you selling a property? <Link className="font-bold text-green underline underline-offset-4" href="/sell">List your property</Link></p></div></section>

    <Section className="bg-white"><SectionHead eyebrow="CURATED FOR YOU" title="Explore properties" text="Shortlist homes with the essential numbers already in view." action={['See all properties','/properties']}/><div className="mb-7 flex gap-2">{cities.map(c=><button key={c} onClick={()=>setCity(c)} className={`rounded-full px-5 py-2.5 text-sm font-bold ${city===c?'bg-ink text-white':'bg-cream text-ink/60'}`}>{c}</button>)}</div>{isLoading?<Skeleton/>:isError?<State title="We couldn’t load properties" action="Try again" onClick={refetch}/>:visible.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map(p=><PropertyCard key={p.id} property={p}/>)}</div>:<State title={`No properties found in ${city}`} action="Explore all"/>}{data?.demo&&<p className="mt-5 text-xs text-ink/40">Preview listings shown for product demonstration. Availability and prices are illustrative.</p>}</Section>

    <Section className="bg-cream"><div className="grid items-start gap-12 lg:grid-cols-[.72fr_1.28fr]"><div className="lg:sticky lg:top-28"><p className="eyebrow">DECIDE WITH CONTEXT</p><h2 className="section-title mt-4">Your property.<br/>Your finances.<br/><em>Your decision.</em></h2><p className="mt-6 max-w-md leading-7 text-ink/60">We bring the price, total cost, EMI, rental potential and risk into one clear view—then explain what points toward buy, wait or avoid.</p><div className="mt-8 flex flex-wrap gap-2 text-xs font-bold"><span className="status buy">BUY</span><span className="status wait">WAIT</span><span className="status avoid">AVOID</span></div></div><RecommendationPreview/></div></Section>

    <Section className="bg-white"><SectionHead eyebrow="FINANCIAL TOOLKIT" title="Popular tools" text="Turn a listing into numbers you can act on." action={['View all tools','/tools']}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tools.map(([icon,title,text,href])=>{const Icon=Icons[icon];return <Link key={title} href={href} className="tool-card"><span className="icon-box"><Icon/></span><span><b className="block font-serif text-xl">{title}</b><small className="mt-1 block text-sm leading-5 text-ink/50">{text}</small><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-green">Use tool <Icons.ArrowUpRight size={15}/></span></span></Link>})}</div></Section>

    <Section className="border-y border-ink/8 bg-[#edf1ec]"><SectionHead eyebrow="A BETTER BUYING PROCESS" title="How Your Home works"/><div className="grid gap-px overflow-hidden rounded-[28px] border border-ink/10 bg-ink/10 md:grid-cols-4">{[['01','FIND','Find a property in your city'],['02','COST','Calculate its true cost'],['03','ANALYZE','Check finances and risk'],['04','DECIDE','Get a clear recommendation']].map(([n,t,d],i)=><div key={t} className="relative bg-[#edf1ec] p-7"><span className="text-xs font-bold text-green">{n}</span><h3 className="mt-12 font-serif text-3xl">{t}</h3><p className="mt-3 text-sm text-ink/55">{d}</p>{i<3&&<Icons.ArrowRight className="absolute right-5 top-7 hidden text-ink/25 md:block" size={18}/>}</div>)}</div></Section>

    <Section className="bg-white"><div className="seller-grid"><div className="p-7 md:p-12"><p className="eyebrow !text-[#a6cbbd]">FOR PROPERTY OWNERS</p><h2 className="mt-5 font-serif text-5xl leading-[.95] text-white md:text-6xl">Have a property to sell?</h2><p className="mt-6 max-w-lg leading-7 text-white/60">List your property on Your Home and connect with buyers in Gurugram and Ghaziabad.</p><Link className="btn-light mt-8" href="/sell">List your property <Icons.ArrowUpRight size={16}/></Link></div><div className="m-4 rounded-[24px] bg-[#f5f1e8] p-5 md:m-7 md:p-7"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-widest text-ink/45">Listing preview</span><span className="rounded-full bg-green/10 px-3 py-1 text-xs font-bold text-green">● ACTIVE</span></div><div className="mt-9 flex items-center gap-4"><div className="h-16 w-20 rounded-xl bg-[url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=300&q=70')] bg-cover bg-center"/><div><h3 className="font-serif text-xl">Palm Grove Residence</h3><p className="text-sm text-ink/50">Sector 57, Gurugram</p></div><b className="ml-auto hidden sm:block">₹ 2.85 Cr</b></div><div className="mt-8 grid grid-cols-3 rounded-2xl bg-white p-5 text-center"><span><b className="block text-xl">—</b><small className="text-ink/45">Views</small></span><span className="border-x border-ink/10"><b className="block text-xl">—</b><small className="text-ink/45">Leads</small></span><span><b className="block text-xl">1</b><small className="text-ink/45">Listing</small></span></div><p className="mt-4 text-xs text-ink/40">Live metrics appear after your listing is published.</p></div></div></Section>

    <Section className="bg-cream"><div className="grid gap-14 lg:grid-cols-2"><div><SectionHead eyebrow="KNOW YOUR MARKET" title="Real estate insights" action={['View all insights','/insights']}/><div className="space-y-3">{data?.insights?.map(item=>{const Icon=Icons[item.icon];return <Link href="/insights" key={item.title} className="flex gap-4 rounded-2xl border border-ink/10 bg-white p-5 hover:border-green"><span className="icon-box shrink-0"><Icon/></span><span><small className="font-bold text-green">{item.eyebrow}</small><b className="mt-1 block font-serif text-xl">{item.title}</b><span className="mt-1 block text-sm text-ink/50">{item.text}</span></span></Link>})}</div></div><div><SectionHead eyebrow="HOUSING SUPPORT" title="Government benefits" action={['Explore schemes','/schemes']}/><div className="space-y-3">{data?.schemes?.map(s=><Link href="/schemes" key={s.name} className="block rounded-2xl border border-ink/10 bg-white p-5 hover:border-green"><div className="flex items-start gap-3"><Icons.Landmark className="mt-1 text-gold" size={20}/><div><b className="font-serif text-xl">{s.name}</b><p className="mt-2 text-sm leading-6 text-ink/55">{s.benefit}</p><span className="mt-3 inline-block rounded-full bg-gold/10 px-3 py-1 text-xs font-bold text-[#85531e]">{s.eligibility}</span></div></div></Link>)}</div></div></div></Section>

    <section className="bg-gold px-5 py-16 md:py-24"><div className="mx-auto max-w-4xl text-center"><p className="eyebrow !text-ink/60">YOUR NEXT MOVE, MADE CLEARER</p><h2 className="mt-5 font-serif text-5xl leading-[.95] md:text-7xl">Ready to make a smarter property decision?</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link className="btn-dark" href="/properties">Explore properties <Icons.ArrowUpRight size={16}/></Link><Link className="btn-ghost" href="/calculators/affordability">Check affordability</Link></div></div></section>
  </main><Footer/></>;
}

function Section({children,className=''}){return <section className={`px-5 py-16 md:py-24 lg:px-10 ${className}`}><div className="mx-auto max-w-[1360px]">{children}</div></section>}
function SectionHead({eyebrow,title,text,action}){return <div className="mb-9 flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="section-title mt-3">{title}</h2>{text&&<p className="mt-3 text-ink/55">{text}</p>}</div>{action&&<Link className="inline-flex items-center gap-2 text-sm font-bold text-green" href={action[1]}>{action[0]} <Icons.ArrowUpRight size={16}/></Link>}</div>}
function Skeleton(){return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-[460px] animate-pulse rounded-[24px] bg-cream"/>)}</div>}
function State({title,action,onClick}){return <div className="rounded-3xl border border-dashed border-ink/20 p-12 text-center"><h3 className="font-serif text-2xl">{title}</h3>{action&&<button className="btn-outline mt-5" onClick={onClick}>{action}</button>}</div>}
