'use client';
import Link from 'next/link';
import { useMemo } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
import { amountToIndianWords, money, percent } from '@/utils/currency';
import { calculateAffordability, calculateBuyVsRent, calculateEmi, calculateRentalRoi, calculateRisk, calculateTrueCost } from '@/lib/calculators';
import CalculatorDisclaimer from './CalculatorDisclaimer';

const configs = {
  emi: { title:'EMI Calculator', text:'Estimate your home-loan monthly payment and complete interest cost.', defaults:{propertyPrice:12000000,downPayment:2400000,interestRate:8.5,tenureYears:20}, fields:[['propertyPrice','Property price'],['downPayment','Down payment'],['interestRate','Interest rate (%)'],['tenureYears','Loan tenure (years)']] },
  'true-cost': { title:'True Cost Calculator', text:'See beyond the listing price with taxes, charges and loan interest together.', defaults:{propertyPrice:12000000,downPayment:2400000,stampDuty:840000,registration:120000,brokerage:120000,interiors:400000,interestRate:8.5,tenureYears:20}, fields:[['propertyPrice','Property price'],['downPayment','Down payment'],['stampDuty','Stamp duty'],['registration','Registration charges'],['brokerage','Brokerage'],['interiors','Interiors / furnishing'],['interestRate','Interest rate (%)'],['tenureYears','Loan tenure (years)']] },
  affordability: { title:'Affordability Check', text:'Understand whether a property leaves enough room in your monthly cash flow.', defaults:{monthlyIncome:150000,coApplicantIncome:0,monthlyExpenses:45000,existingEmi:10000,otherObligations:5000,savings:4000000,downPayment:2400000,emergencyFund:800000,propertyPrice:12000000,interestRate:8.5,tenureYears:20}, fields:[['monthlyIncome','Monthly take-home income'],['coApplicantIncome','Co-applicant income'],['monthlyExpenses','Household expenses'],['existingEmi','Existing EMI'],['otherObligations','Other obligations'],['savings','Total liquid savings'],['downPayment','Down payment'],['emergencyFund','Desired emergency fund'],['propertyPrice','Property price'],['interestRate','Interest rate (%)'],['tenureYears','Loan tenure (years)']] },
  'rental-roi': { title:'Rental ROI Calculator', text:'Estimate gross and net rental yield after vacancy and recurring property costs.', defaults:{propertyPrice:12000000,monthlyRent:42000,annualMaintenance:60000,propertyTax:18000,vacancyPercent:5,annualExpenses:12000}, fields:[['propertyPrice','Property price'],['monthlyRent','Expected monthly rent'],['annualMaintenance','Annual maintenance'],['propertyTax','Property tax'],['vacancyPercent','Vacancy estimate (%)'],['annualExpenses','Other annual expenses']] },
  'risk-analysis': { title:'Risk Analysis', text:'Get a transparent view of the financial and property factors to consider.', defaults:{monthlyIncome:150000,monthlyExpenses:45000,existingEmi:10000,savings:4000000,downPayment:2400000,emergencyFund:800000,propertyPrice:12000000,interestRate:8.5,tenureYears:20,netYield:3.4}, fields:[['monthlyIncome','Monthly take-home income'],['monthlyExpenses','Household expenses'],['existingEmi','Existing EMI'],['savings','Total liquid savings'],['downPayment','Down payment'],['emergencyFund','Desired emergency fund'],['propertyPrice','Property price'],['interestRate','Interest rate (%)'],['tenureYears','Loan tenure (years)'],['netYield','Estimated rental yield (%)']] },
  'buy-vs-rent': { title:'Buy vs Rent', text:'Compare ownership costs and rental flexibility over the years you expect to stay.', defaults:{propertyPrice:12000000,downPayment:2400000,interestRate:8.5,tenureYears:20,registration:960000,annualMaintenance:60000,propertyTax:18000,monthlyRent:30000,securityDeposit:60000,rentIncrease:5,years:5}, fields:[['propertyPrice','Property price'],['downPayment','Down payment'],['interestRate','Interest rate (%)'],['tenureYears','Loan tenure (years)'],['registration','Registration and upfront charges'],['annualMaintenance','Annual maintenance'],['propertyTax','Property tax'],['monthlyRent','Current monthly rent'],['securityDeposit','Security deposit'],['rentIncrease','Annual rent increase (%)'],['years','Expected years in home']] }
};
const schema = z.record(z.coerce.number().min(0, 'Use a value of zero or more.'));

export default function CalculatorTool({ type }) {
  const config = configs[type];
  const { register, watch, setValue, formState:{errors} } = useForm({ resolver:zodResolver(schema), defaultValues:config.defaults, mode:'onChange' });
  const values = watch();
  const result = useMemo(() => calculate(type, values), [type, values]);
  return <main className="bg-cream"><section className="border-b border-ink/10 bg-[#eef1ea]"><div className="mx-auto max-w-[1360px] px-5 py-12 lg:px-10"><p className="eyebrow">PROPERTY FINANCE TOOL</p><h1 className="mt-3 font-serif text-5xl tracking-[-.04em]">{config.title}</h1><p className="mt-4 max-w-2xl leading-7 text-ink/60">{config.text}</p></div></section><section className="mx-auto max-w-[1360px] px-5 py-8 md:py-12 lg:px-10"><div className="grid gap-6 lg:grid-cols-[.95fr_1.05fr]"><form className="rounded-[26px] border border-ink/10 bg-white p-5 md:p-7"><h2 className="font-serif text-3xl">Your inputs</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{config.fields.map(([name,label])=><CalculatorField key={name} name={name} label={label} value={Number(values[name])||0} register={register} setValue={setValue} error={errors[name]?.message}/>)}</div><CalculatorDisclaimer/></form><section aria-live="polite" className="rounded-[26px] bg-[#15352c] p-5 text-white md:p-7"><p className="eyebrow !text-[#a6cbbd]">LIVE ESTIMATE</p><Result type={type} result={result}/><Link className="btn-light mt-7" href="/smart-recommendation">Get smart recommendation <ArrowUpRight size={16}/></Link></section></div></section></main>;
}
function CalculatorField({name,label,value,register,setValue,error}){const percentage=/rate|yield|vacancy|increase/i.test(name),years=/tenure|years/i.test(name),currency=!percentage&&!years,max=currency?Math.max(10000000,Math.ceil(value/100000)*100000):percentage?30:40,step=currency?name.includes('monthly')||name.includes('Rent')?1000:100000:percentage?.1:1;return <label className="calc-field"><span>{label}</span><input type="number" min="0" step={step} {...register(name)}/>{currency&&<><small className="text-ink/55">{amountToIndianWords(value)}</small><input aria-label={`${label} slider`} aria-valuemin="0" aria-valuemax={max} aria-valuenow={value} className="mt-2 w-full accent-green" type="range" min="0" max={max} step={step} value={Math.min(value,max)} onChange={e=>setValue(name,Number(e.target.value),{shouldValidate:true,shouldDirty:true})}/><small className="flex justify-between text-ink/45"><span>₹0</span><span>{money(max)}</span></small></>}{!currency&&<input aria-label={`${label} slider`} className="mt-2 w-full accent-green" type="range" min="0" max={max} step={step} value={Math.min(value,max)} onChange={e=>setValue(name,Number(e.target.value),{shouldValidate:true,shouldDirty:true})}/>} {error&&<small>{error}</small>}</label>}
function calculate(type,v){ if(type==='emi') return calculateEmi({loanAmount:v.propertyPrice-v.downPayment,interestRate:v.interestRate,tenureYears:v.tenureYears}); if(type==='true-cost') return calculateTrueCost(v); if(type==='affordability') return calculateAffordability(v); if(type==='rental-roi') return calculateRentalRoi(v); if(type==='risk-analysis'){const affordability=calculateAffordability(v);return {...affordability,...calculateRisk({...affordability,emergencyFund:v.emergencyFund,possessionStatus:'Ready to Move',netYield:v.netYield})};} return calculateBuyVsRent(v); }
function Result({type,result}){ if(type==='emi') return <><h2 className="mt-4 font-serif text-4xl">{money(result.emi,' / month')}</h2><p className="mt-1 text-white/55">Estimated monthly EMI</p><Metrics values={[["Principal",money(result.principal)],["Total interest",money(result.totalInterest)],["Total payment",money(result.totalPayment)],["Tenure",`${result.payments/12} years`]]}/></>; if(type==='true-cost') return <><h2 className="mt-4 font-serif text-4xl">{money(result.trueCost)}</h2><p className="mt-1 text-white/55">Estimated true ownership cost</p><Metrics values={[["Listed price",money(result.propertyPrice)],["Upfront purchase cost",money(result.upfrontCharges)],["Loan interest",money(result.totalInterest)],["Loan amount",money(result.loanAmount)]]}/></>; if(type==='affordability') return <><Status status={result.status}/><Metrics values={[["Proposed EMI",money(result.emi,' / month')],["EMI burden",percent(result.emiBurden)],["Monthly cash remaining",money(result.cashRemaining)],["Savings after purchase",money(result.savingsRemaining)]]}/></>; if(type==='rental-roi') return <><h2 className="mt-4 font-serif text-4xl">{percent(result.netYield)}</h2><p className="mt-1 text-white/55">Estimated net rental yield</p><Metrics values={[["Annual gross rent",money(result.grossRent)],["Gross yield",percent(result.grossYield)],["Annual expenses",money(result.expenses+result.vacancyLoss)],["Net rental income",money(result.netIncome)]]}/></>; if(type==='risk-analysis') return <><Status status={result.level}/><Metrics values={[["EMI burden",percent(result.emiBurden)],["Monthly cash remaining",money(result.cashRemaining)],["Savings after purchase",money(result.savingsRemaining)],["Risk factors",String(result.flags.length)]]}/><ul className="mt-5 space-y-2 text-sm text-white/65">{result.flags.length?result.flags.map(f=><li key={f}>• {f}</li>):<li className="flex gap-2"><CheckCircle2 size={16}/> No high-pressure factors from these inputs.</li>}</ul></>; return <><p className="eyebrow !text-[#a6cbbd] mt-4">NEUTRAL COMPARISON</p><h2 className="mt-2 font-serif text-3xl">{result.conclusion}</h2><Metrics values={[["Buying total, 5 years",money(result.buyingTotal)],["Renting total, 5 years",money(result.rentTotal)],["Buying EMI",money(result.emi,' / month')],["Monthly difference",money(result.monthlyDifference)]]}/></>; }
function Status({status}){return <><h2 className="mt-4 font-serif text-4xl">{status}</h2><p className="mt-1 text-white/55">Based on the information provided</p></>}
function Metrics({values}){return <div className="mt-7 grid grid-cols-2 gap-3">{values.map(([label,value])=><div className="rounded-2xl bg-white/[.07] p-4" key={label}><span className="block text-xs text-white/50">{label}</span><b className="mt-1 block text-sm">{value}</b></div>)}</div>}
