'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Info,TriangleAlert} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {amountToIndianWords,money,percent} from '@/utils/currency';
import {calculateRentalROI,calculateRentalScenarios} from '@/lib/calculators/rentalRoi';
import CalculatorDisclaimer from './CalculatorDisclaimer';

const steps=['Property','Rental Income','Expenses','Financing','Growth & Holding','Results'];
const initial={propertyPrice:8000000,trueAcquisitionCost:8600000,knowsTrueCost:true,propertyType:'Apartment',propertyArea:1200,location:'',monthlyRent:35000,otherMonthlyIncome:0,securityDeposit:70000,vacancyRate:5,propertyTax:25000,societyCharges:35000,insurance:0,repairReserve:30000,managementMode:'percent',managementFeeRate:0,managementFeeAmount:0,otherAnnualExpenses:0,financed:false,loanAmount:5000000,downPayment:3000000,interestRate:8.5,tenureYears:20,initialSetupCosts:0,rentGrowthRate:5,appreciationRate:5,holdingYears:5,sellingCostRate:2,targetNetYield:5};
const scenarioDefaults={Conservative:{vacancyRate:10,rentGrowthRate:3,appreciationRate:3,repairReserve:45000},Expected:{vacancyRate:5,rentGrowthRate:5,appreciationRate:5,repairReserve:30000},Optimistic:{vacancyRate:2,rentGrowthRate:7,appreciationRate:7,repairReserve:20000}};
const compact=v=>{const n=Math.abs(Number(v)||0);return `${v<0?'-':''}₹${n>=10000000?(n/10000000).toFixed(2)+'Cr':n>=100000?(n/100000).toFixed(2)+'L':n>=1000?Math.round(n/1000)+'K':Math.round(n)}`};

export default function RentalInvestmentCalculator(){
 const[form,setForm]=useState(initial),[step,setStep]=useState(0),[projectionYears,setProjectionYears]=useState(5),[scenarios,setScenarios]=useState(scenarioDefaults);
 const activeForm=useMemo(()=>({...form,trueAcquisitionCost:form.knowsTrueCost?form.trueAcquisitionCost:0}),[form]);
 const result=useMemo(()=>calculateRentalROI(activeForm),[activeForm]);
 const scenarioResults=useMemo(()=>calculateRentalScenarios(activeForm,scenarios),[activeForm,scenarios]);
 const set=(name,value)=>setForm(x=>({...x,[name]:value}));
 const visibleProjection=result.projection.slice(0,projectionYears), allocation=[['Property Tax',form.propertyTax,'#386c5b'],['Maintenance',form.societyCharges,'#78a18f'],['Vacancy',result.vacancyLoss,'#d8a34a'],['Repairs',form.repairReserve,'#bd725d'],['Management',result.managementFee,'#8a7564'],['Other',form.insurance+form.otherAnnualExpenses,'#a9a29a'],['Loan Payments',result.annualDebtService,'#253b35'],['Net Cash Flow',Math.max(0,result.annualCashFlow),'#63a374']].filter(x=>x[1]>0);
 return <main className="bg-cream text-ink"><header className="border-b border-ink/10 bg-[#eef1ea]"><div className="mx-auto max-w-[1360px] px-5 py-10 lg:px-10"><p className="eyebrow">PROPERTY FINANCE TOOL</p><h1 className="mt-3 font-serif text-4xl tracking-[-.04em] md:text-5xl">Rental Investment Performance</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-ink/60">See the return you may earn after vacancy, operating costs, acquisition cost and optional financing.</p></div></header>
 <nav className="sticky top-0 z-20 overflow-x-auto border-b border-ink/10 bg-cream/95 backdrop-blur"><ol className="mx-auto flex min-w-max max-w-[1360px] px-5 lg:px-10">{steps.map((label,i)=><li key={label}><button onClick={()=>setStep(i)} className={`border-b-2 px-4 py-4 text-left text-xs font-bold ${step===i?'border-green text-green':'border-transparent text-ink/45'}`}><span className="mr-2 font-serif">0{i+1}</span>{label}</button></li>)}</ol></nav>
 <div className="mx-auto max-w-[1360px] px-5 py-8 lg:px-10"><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className="min-w-0 rounded-3xl border border-ink/10 bg-white p-5 md:p-7">
 {step===0&&<Step title="Property" intro="Start with the listing price and the most complete acquisition cost available."><MoneyField label="Property listing price" name="propertyPrice" value={form.propertyPrice} onChange={set} max={100000000}/><div className="grid gap-4 sm:grid-cols-2"><Select label="Property type" value={form.propertyType} onChange={v=>set('propertyType',v)} options={['Apartment','Villa','Independent House','Plot / Other']}/><TextField label="Location" value={form.location} onChange={v=>set('location',v)} placeholder="City or locality"/><NumberField label="Property area (sq.ft.)" value={form.propertyArea} onChange={v=>set('propertyArea',v)}/></div><Choice label="Do you know the True Acquisition Cost?" value={form.knowsTrueCost} onChange={v=>set('knowsTrueCost',v)} yes="Yes" no="No"/>{form.knowsTrueCost?<MoneyField label="True acquisition cost" name="trueAcquisitionCost" value={form.trueAcquisitionCost} onChange={set} max={120000000}/>:<div className="rounded-2xl bg-[#eef4ef] p-5"><b className="text-sm">DON'T KNOW THE TRUE COST?</b><p className="mt-2 text-xs leading-5 text-ink/60">The listing price may exclude stamp duty, registration, GST, legal and other acquisition costs.</p><Link className="btn-outline mt-4 !min-h-9 !text-xs" href="/calculators/true-cost">Calculate True Cost <ArrowRight size={14}/></Link></div>}</Step>}
 {step===1&&<Step title="Rental Income" intro="Deposits stay separate and are not treated as income."><MoneyField label="Expected monthly rent" name="monthlyRent" value={form.monthlyRent} onChange={set} max={500000}/><MoneyField label="Other monthly rental income" name="otherMonthlyIncome" value={form.otherMonthlyIncome} onChange={set} max={200000}/><PercentField label="Expected vacancy" name="vacancyRate" value={form.vacancyRate} onChange={set} max={30}/><MoneyField label="Security deposit" name="securityDeposit" value={form.securityDeposit} onChange={set} max={2000000}/><Note>Security deposits are not counted as rental income.</Note></Step>}
 {step===2&&<Step title="Operating Expenses" intro="Enter annual costs only. Loan payments remain separate from NOI."><div className="grid gap-4 sm:grid-cols-2"><MoneyField label="Annual property tax" name="propertyTax" value={form.propertyTax} onChange={set}/><MoneyField label="Annual society / maintenance" name="societyCharges" value={form.societyCharges} onChange={set}/><MoneyField label="Annual insurance" name="insurance" value={form.insurance} onChange={set}/><MoneyField label="Annual repair reserve (assumption)" name="repairReserve" value={form.repairReserve} onChange={set}/><MoneyField label="Other annual expenses" name="otherAnnualExpenses" value={form.otherAnnualExpenses} onChange={set}/></div><Select label="Management fee method" value={form.managementMode} onChange={v=>set('managementMode',v)} options={['percent','amount']} labels={['% of effective rent','Annual ₹ amount']}/>{form.managementMode==='percent'?<PercentField label="Management fee" name="managementFeeRate" value={form.managementFeeRate} onChange={set} max={20}/>:<MoneyField label="Annual management fee" name="managementFeeAmount" value={form.managementFeeAmount} onChange={set}/>}</Step>}
 {step===3&&<Step title="Financing" intro="Cash purchase is the default. Financing affects cash flow, not operating expenses."><Choice label="Is this property financed?" value={form.financed} onChange={v=>set('financed',v)} yes="Yes — Home / Investment Loan" no="No — Cash Purchase"/>{form.financed?<><MoneyField label="Loan amount" name="loanAmount" value={form.loanAmount} onChange={set} max={form.propertyPrice}/><MoneyField label="Down payment" name="downPayment" value={form.downPayment} onChange={set} max={form.propertyPrice}/><div className="grid gap-4 sm:grid-cols-2"><PercentField label="Annual interest rate" name="interestRate" value={form.interestRate} onChange={set} max={20}/><NumberField label="Loan tenure (years)" value={form.tenureYears} onChange={v=>set('tenureYears',v)} min={1} max={40}/></div><MoneyField label="Initial setup costs paid in cash" name="initialSetupCosts" value={form.initialSetupCosts} onChange={set}/>{form.loanAmount>form.propertyPrice&&<Warning>Loan amount exceeds the listing price. Review whether the funding assumption is realistic.</Warning>}</>:<Note>Loan inputs and debt-service metrics are not applicable for a cash purchase.</Note>}</Step>}
 {step===4&&<Step title="Growth & Holding" intro="Growth rates are assumptions, not guaranteed returns."><div className="grid gap-4 sm:grid-cols-2"><PercentField label="Annual rent growth" name="rentGrowthRate" value={form.rentGrowthRate} onChange={set} max={15}/><PercentField label="Property appreciation" name="appreciationRate" value={form.appreciationRate} onChange={set} max={15}/><Select label="Holding period" value={String(form.holdingYears)} onChange={v=>set('holdingYears',Number(v))} options={['1','3','5','10','15','20']} labels={['1 year','3 years','5 years','10 years','15 years','20 years']}/><PercentField label="Expected selling cost" name="sellingCostRate" value={form.sellingCostRate} onChange={set} max={10}/></div><Warning>Property appreciation is an assumption, not a guaranteed return.</Warning></Step>}
 {step===5&&<Results result={result} form={form} onFormChange={set} allocation={allocation} projection={visibleProjection} projectionYears={projectionYears} setProjectionYears={setProjectionYears} scenarios={scenarios} setScenarios={setScenarios} scenarioResults={scenarioResults}/>} 
 {step<5&&<div className="mt-8 flex justify-between"><button className="btn-outline disabled:opacity-30" disabled={!step} onClick={()=>setStep(x=>x-1)}>Previous</button><button className="btn-green" onClick={()=>setStep(x=>x+1)}>Continue <ArrowRight size={15}/></button></div>}</section><Live result={result}/></div><CalculatorDisclaimer/></div></main>;
}

function Step({title,intro,children}){return <><p className="eyebrow">ENTER ASSUMPTIONS</p><h2 className="mt-2 font-serif text-3xl">{title}</h2><p className="mt-2 text-sm text-ink/55">{intro}</p><div className="mt-7 space-y-5">{children}</div></>}
function baseNumber(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,n):0}
function MoneyField({label,name,value,onChange,max=10000000}){const dynamicMax=Math.max(max,Math.ceil(baseNumber(value)/100000)*100000),step=dynamicMax<=500000?1000:100000;return <label className="block"><span className="text-xs font-bold">{label}</span><div className="mt-2 flex items-center rounded-xl border border-ink/15 px-3 focus-within:border-green"><span className="text-ink/45">₹</span><input className="h-11 w-full px-2 outline-none" type="number" min="0" value={value} onChange={e=>onChange(name,baseNumber(e.target.value))}/></div><small className="mt-1 block text-[11px] text-green">{amountToIndianWords(value)}</small><input aria-label={`${label} slider`} className="mt-3 w-full accent-green" type="range" min="0" max={dynamicMax} step={step} value={Math.min(value,dynamicMax)} onChange={e=>onChange(name,Number(e.target.value))}/><span className="flex justify-between text-[10px] text-ink/40"><span>₹0</span><span>{money(dynamicMax)}</span></span></label>}
function PercentField({label,name,value,onChange,max}){return <label className="block"><span className="flex justify-between text-xs font-bold"><span>{label}</span><output>{percent(value)}</output></span><input className="mt-3 w-full accent-green" type="range" min="0" max={max} step="0.1" value={value} onChange={e=>onChange(name,Number(e.target.value))}/><input className="mt-2 h-10 w-28 rounded-lg border border-ink/15 px-3 text-sm" type="number" min="0" max={max} step="0.1" value={value} onChange={e=>onChange(name,baseNumber(e.target.value))}/></label>}
function NumberField({label,value,onChange,min=0,max}){return <label className="block"><span className="text-xs font-bold">{label}</span><input className="mt-2 h-11 w-full rounded-xl border border-ink/15 px-3" type="number" min={min} max={max} value={value} onChange={e=>onChange(baseNumber(e.target.value))}/></label>}
function TextField({label,value,onChange,placeholder}){return <label className="block"><span className="text-xs font-bold">{label}</span><input className="mt-2 h-11 w-full rounded-xl border border-ink/15 px-3" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options,labels=options}){return <label className="block"><span className="text-xs font-bold">{label}</span><select className="mt-2 h-11 w-full rounded-xl border border-ink/15 bg-white px-3" value={value} onChange={e=>onChange(e.target.value)}>{options.map((x,i)=><option key={x} value={x}>{labels[i]}</option>)}</select></label>}
function Choice({label,value,onChange,yes,no}){return <fieldset><legend className="text-xs font-bold">{label}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{[[true,yes],[false,no]].map(([v,l])=><button type="button" key={l} onClick={()=>onChange(v)} className={`rounded-xl border p-3 text-left text-xs font-bold ${value===v?'border-green bg-[#eef4ef] text-green':'border-ink/10'}`}>{value===v?'●':'○'} &nbsp;{l}</button>)}</div></fieldset>}
function Note({children}){return <p className="flex gap-2 rounded-xl bg-[#eef4ef] p-3 text-xs text-ink/65"><Info size={16}/>{children}</p>}; function Warning({children}){return <p className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><TriangleAlert size={16}/>{children}</p>}
function Live({result}){return <aside className="h-fit rounded-3xl bg-[#15352c] p-6 text-white xl:sticky xl:top-24"><p className="eyebrow !text-[#a6cbbd]">LIVE SUMMARY</p><h2 className="mt-3 font-serif text-4xl">{percent(result.netRentalYield)}</h2><p className="text-xs text-white/55">Net rental yield</p><div className="mt-6 grid grid-cols-2 gap-3">{[['NOI / year',money(result.noi)],['Effective income',money(result.effectiveRentalIncome)],[result.monthlyCashFlow<0?'Monthly deficit':'Monthly surplus',money(Math.abs(result.monthlyCashFlow))],['Break-even rent',money(result.breakEvenRent)]].map(([l,v])=><div className="rounded-xl bg-white/[.07] p-3" key={l}><span className="text-[10px] text-white/50">{l}</span><b className="mt-1 block text-xs">{v}</b></div>)}</div><div className="mt-5 border-t border-white/10 pt-5 text-xs"><span className="text-white/50">ROI calculated using</span><b className="mt-1 block">{result.usesTrueCost?'True Acquisition Cost':'Listing Price'} · {money(result.acquisitionCost)}</b>{!result.usesTrueCost&&<small className="mt-1 block text-amber-200">True Cost not provided.</small>}</div></aside>}

function Results({result,form,allocation,projection,projectionYears,setProjectionYears,scenarios,setScenarios,scenarioResults}){const flow=[['Gross annual income',result.grossAnnualIncome],['Vacancy loss',-result.vacancyLoss],['Operating expenses',-result.totalOperatingExpenses],['NOI',result.noi],['Loan payments',-result.annualDebtService],['Annual cash flow',result.annualCashFlow]];return <><p className="eyebrow">YOUR RENTAL INVESTMENT REPORT</p><h2 className="mt-2 font-serif text-3xl">Performance dashboard</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Hero label="Net rental yield" value={percent(result.netRentalYield)}/><Hero label="Net operating income" value={`${compact(result.noi)} / year`}/><Hero label={result.monthlyCashFlow<0?'Monthly cash deficit':'Monthly cash surplus'} value={`${result.monthlyCashFlow>=0?'+':''}${money(Math.abs(result.monthlyCashFlow))}`} tone={result.monthlyCashFlow<0?'bad':'good'}/>{form.financed&&<Hero label="Cash-on-cash return" value={percent(result.cashOnCashReturn)}/>}</div>
 <Panel title="Investment summary"><dl className="grid gap-x-8 gap-y-3 text-xs sm:grid-cols-2">{[['Listing price',result.form.propertyPrice],['True acquisition cost',result.form.trueAcquisitionCost||'Not provided'],['Cash invested',result.cashInvested],['Loan amount',form.financed?result.form.loanAmount:'Cash purchase'],['Expected monthly rent',result.form.monthlyRent],['Effective annual rent',result.effectiveRentalIncome],['Operating expenses',result.totalOperatingExpenses],['NOI',result.noi]].map(([l,v])=><div className="flex justify-between border-b border-ink/10 pb-2" key={l}><dt className="text-ink/55">{l}</dt><dd className="font-bold">{typeof v==='number'?money(v):v}</dd></div>)}</dl></Panel>
 <div className="grid gap-5 lg:grid-cols-2"><Panel title="Rental income waterfall"><div className="space-y-2">{flow.map(([l,v],i)=><div key={l} className={`flex items-center justify-between rounded-lg p-3 text-xs ${i===flow.length-1?'bg-[#15352c] text-white':'bg-[#f4f5f1]'}`}><span>{l}</span><b>{v<0?'-':''}{money(Math.abs(v))}</b></div>)}</div></Panel><Panel title="Annual rental income allocation"><div className="h-64"><ResponsiveContainer><PieChart><Pie data={allocation.map(([name,value,color])=>({name,value,color}))} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="78%">{allocation.map(x=><Cell key={x[0]} fill={x[2]}/>)}</Pie><Tooltip formatter={v=>money(v)}/><Legend wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></div>{result.annualCashFlow<0&&<Warning>Annual financing deficit: {money(Math.abs(result.annualCashFlow))}. Deficits are shown separately, never as negative donut slices.</Warning>}</Panel></div>
 <Panel title="5 / 10-year projection" action={<div className="flex gap-1">{[5,10].map(y=><button className={`rounded-full px-3 py-1 text-[10px] font-bold ${projectionYears===y?'bg-green text-white':'bg-ink/5'}`} key={y} onClick={()=>setProjectionYears(y)}>{y} years</button>)}</div>}><div className="h-72"><ResponsiveContainer><LineChart data={projection}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>money(v)}/><Legend/><Line dataKey="propertyValue" name="Property value" stroke="#155f4b" dot={false}/><Line dataKey="annualRent" name="Annual rent" stroke="#d39a3e" dot={false}/><Line dataKey="noi" name="NOI" stroke="#6d8f82" dot={false}/><Line dataKey="annualCashFlow" name="Cash flow" stroke="#9b5d4d" dot={false}/></LineChart></ResponsiveContainer></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[11px]"><thead><tr className="border-b border-ink/10">{['Year','Rent','NOI','Cash Flow','Est. Property Value'].map(x=><th className="py-2" key={x}>{x}</th>)}</tr></thead><tbody>{projection.filter((_,i)=>i<3||i===4||i===9).map(x=><tr className="border-b border-ink/5" key={x.year}><td className="py-2">{x.year}</td><td>{money(x.annualRent)}</td><td>{money(x.noi)}</td><td>{money(x.annualCashFlow)}</td><td>{money(x.propertyValue)}</td></tr>)}</tbody></table></div></Panel>
 <Panel title="Scenario analysis"><p className="text-xs text-ink/55">Assumptions are visible and editable. Results are calculated, not hardcoded.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-[11px]"><thead><tr><th className="text-left">Assumption / result</th>{Object.keys(scenarios).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{[['Vacancy','vacancyRate','%'],['Rent growth','rentGrowthRate','%'],['Appreciation','appreciationRate','%'],['Repair reserve','repairReserve','₹']].map(([label,key,suffix])=><tr key={key}><td>{label}</td>{Object.entries(scenarios).map(([name,s])=><td className="p-1" key={name}><input aria-label={`${name} ${label}`} className="w-24 rounded border border-ink/10 p-1 text-center" type="number" value={s[key]} onChange={e=>setScenarios(all=>({...all,[name]:{...all[name],[key]:baseNumber(e.target.value)}}))}/>{suffix}</td>)}</tr>)}{[['Net yield',r=>percent(r.netRentalYield)],['Monthly cash flow',r=>money(r.monthlyCashFlow)],['5-year ROI',r=>percent(r.totalROI)],['Property value',r=>money(r.estimatedSalePrice)]].map(([label,get])=><tr className="border-t border-ink/10 font-bold" key={label}><td className="py-2">{label}</td>{Object.keys(scenarios).map(n=><td className="text-center" key={n}>{get(scenarioResults[n])}</td>)}</tr>)}</tbody></table></div></Panel>
 <div className="grid gap-5 lg:grid-cols-2"><Panel title="Break-even & target rent"><MetricRow label="Break-even rent" value={`${money(result.breakEvenRent)} / month`}/><MetricRow label="Current rent" value={money(form.monthlyRent)}/><MetricRow label={form.monthlyRent>=result.breakEvenRent?'Buffer above break-even':'Shortfall'} value={`${money(Math.abs(form.monthlyRent-result.breakEvenRent))} / month`}/><hr className="my-4"/><PercentField label="Target net yield" name="targetNetYield" value={form.targetNetYield} onChange={()=>{}} max={12}/><MetricRow label="Required monthly rent" value={money(result.targetRent)}/><MetricRow label="Rent gap" value={`${money(Math.abs(result.targetRent-form.monthlyRent))} / month`}/></Panel><Panel title="Rental investment health"><div className="flex items-end gap-3"><b className="font-serif text-5xl">{result.healthScore}</b><span className="pb-1 text-sm">/ 100 · {result.healthScore>=70?'HEALTHY':result.healthScore>=45?'WATCH MARGINS':'PRESSURED'}</span></div><p className="mt-2 text-[10px] text-ink/50">A YOUR HOME planning score, not a bank or government score.</p>{Object.entries(result.healthParts).map(([k,v])=><div className="mt-3" key={k}><div className="flex justify-between text-[10px]"><span className="capitalize">{k.replace(/([A-Z])/g,' $1')}</span><b>{Math.round(v)}</b></div><div className="mt-1 h-1.5 rounded bg-ink/10"><i className="block h-full rounded bg-green" style={{width:`${v/(k==='expenseLoad'||k==='vacancy'?20:30)*100}%`}}/></div></div>)}</Panel></div>
 <Panel title="Stress tests & holding return"><div className="grid gap-3 sm:grid-cols-2"><Hero label={`At ${form.vacancyRate+5}% vacancy`} value={`${result.vacancyStressCashFlow<0?'Deficit ':'Surplus '}${money(Math.abs(result.vacancyStressCashFlow))}/mo`} tone={result.vacancyStressCashFlow<0?'bad':'good'}/>{form.financed&&<Hero label={`At ${result.interestStress.rate}% interest`} value={`${money(result.interestStress.emi)}/mo EMI`} tone={result.interestStress.monthlyCashFlow<0?'bad':'good'}/>}<Hero label={`${form.holdingYears}-year total ROI`} value={percent(result.totalROI)}/><Hero label="Estimated annualized return" value={percent(result.annualizedReturn)}/></div><div className="mt-4 grid gap-2 text-xs sm:grid-cols-2"><MetricRow label="Estimated sale price" value={money(result.estimatedSalePrice)}/><MetricRow label="Selling costs" value={money(result.sellingCosts)}/><MetricRow label="Outstanding loan" value={money(result.outstandingLoanBalance)}/><MetricRow label="Net sale proceeds" value={money(result.netSaleProceeds)}/></div></Panel><Insights result={result} form={form}/></>}
function Panel({title,action,children}){return <section className="mt-5 rounded-2xl border border-ink/10 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-xl">{title}</h3>{action}</div><div className="mt-4">{children}</div></section>}; function Hero({label,value,tone}){return <div className={`rounded-xl p-4 ${tone==='bad'?'bg-red-50 text-red-900':tone==='good'?'bg-[#eaf4ed]':'bg-[#f4f5f1]'}`}><span className="text-[10px] font-bold uppercase tracking-wider opacity-60">{label}</span><b className="mt-2 block text-lg">{value}</b></div>}; function MetricRow({label,value}){return <div className="flex justify-between gap-3 border-b border-ink/10 py-2 text-xs"><span className="text-ink/55">{label}</span><b className="text-right">{value}</b></div>}
function Insights({result,form}){const items=[[result.noi>=0,'Positive operating income.',result.noi<0],[result.noi>0&&result.annualCashFlow<0,'Financing turns positive NOI into negative monthly cash flow.',true],[form.monthlyRent>=result.breakEvenRent,`Current rent is ${money(Math.abs(form.monthlyRent-result.breakEvenRent))} ${form.monthlyRent>=result.breakEvenRent?'above':'below'} break-even.`,form.monthlyRent<result.breakEvenRent],[result.vacancyStressCashFlow<0,`A ${form.vacancyRate+5}% vacancy assumption produces a monthly deficit.`,true],[result.targetRent>form.monthlyRent,`Target ${form.targetNetYield}% net yield needs about ${money(result.targetRent-form.monthlyRent)} more monthly rent.`,true]].filter(x=>x[0]);return <Panel title="Investment insights"><ul className="space-y-3 text-xs">{items.map(([_,text,warn])=><li className="flex gap-2" key={text}>{warn?<TriangleAlert className="shrink-0 text-amber-700" size={16}/>:<CheckCircle2 className="shrink-0 text-green" size={16}/>}<span>{text}</span></li>)}</ul></Panel>}
