import {calculateEmi,calculateAffordability,calculateBuyVsRent} from './index';
import {calculateRiskAnalysis} from './riskAnalysis';
import {calculateRentalROI} from './rentalRoi';

const n=value=>Math.max(0,Number(value)||0), clamp=(v,min=0,max=100)=>Math.min(max,Math.max(min,v));
const label=score=>score>=80?'STRONG FIT':score>=65?'CONSIDER':score>=50?'CAUTION':'POOR FIT';
const trueCost=(input)=>{const price=n(input.property.price), supplied=n(input.property.trueCost);return{listingPrice:price,governmentCharges:0,estimatedBuyingCosts:Math.max(supplied-price,0),expected:supplied||price,usesProvidedCost:supplied>0};};
function riskInput(input,cost,loanAmount){return{financial:{monthlyIncome:n(input.user.monthlyIncome),coApplicantIncome:n(input.user.coApplicantIncome),existingEmi:n(input.user.existingEmi),householdExpenses:n(input.user.monthlyExpenses),otherCommitments:n(input.user.otherCommitments),currentRent:n(input.user.currentRent),totalSavings:n(input.user.savings),emergencyReserve:n(input.user.emergencyReserve)},property:{listingPrice:n(input.property.price),trueCost:cost.expected},financing:{mode:input.financing.mode==='CASH'?'CASH':'LOAN',loanAmount,downPayment:n(input.financing.downPayment),interestRate:n(input.financing.interestRate),tenureYears:n(input.financing.tenureYears)},rental:{enabled:input.intent.type==='INVESTMENT',monthlyRent:n(input.property.expectedRent),vacancyRate:n(input.rental.vacancyRate),annualExpenses:n(input.rental.annualExpenses)},assumptions:{mildRateIncrease:1,severeRateIncrease:2,mildIncomeDrop:5,severeIncomeDrop:10,mildExpenseIncrease:10,severeExpenseIncrease:20,mildVacancyIncrease:5,severeVacancyIncrease:10}}}
function decision(input,depth=0){const cost=trueCost(input), f=input.financing||{}, isCash=f.mode==='CASH', totalIncome=n(input.user.monthlyIncome)+n(input.user.coApplicantIncome), defaultLoan=Math.max(cost.expected-n(f.downPayment),0), loanAmount=f.mode==='UNDECIDED'?defaultLoan:n(f.loanAmount), emi=isCash?{emi:0,totalInterest:0}:{...calculateEmi({loanAmount,interestRate:n(f.interestRate)||8.5,tenureYears:n(f.tenureYears)||20})};
 const affordability=calculateAffordability({monthlyIncome:n(input.user.monthlyIncome),coApplicantIncome:n(input.user.coApplicantIncome),monthlyExpenses:n(input.user.monthlyExpenses),existingEmi:n(input.user.existingEmi),otherObligations:n(input.user.otherCommitments)+n(input.user.currentRent),savings:n(input.user.savings),downPayment:isCash?cost.expected:n(f.downPayment),emergencyFund:n(input.user.emergencyReserve),propertyPrice:cost.expected,interestRate:n(f.interestRate)||8.5,tenureYears:n(f.tenureYears)||20});
 const risk=calculateRiskAnalysis(riskInput(input,cost,loanAmount)); const rental=input.intent.type==='INVESTMENT'?calculateRentalROI({propertyPrice:n(input.property.price),trueAcquisitionCost:cost.expected,monthlyRent:n(input.property.expectedRent),vacancyRate:n(input.rental.vacancyRate),annualExpenses:n(input.rental.annualExpenses),financed:!isCash,loanAmount,downPayment:n(f.downPayment),interestRate:n(f.interestRate)||8.5,tenureYears:n(f.tenureYears)||20,rentGrowthRate:n(input.rental.rentGrowthRate),appreciationRate:n(input.rental.appreciationRate),holdingYears:n(input.rental.holdingYears)||5}):null;
 const buyVsRent=calculateBuyVsRent({propertyPrice:cost.expected,downPayment:isCash?cost.expected:n(f.downPayment),interestRate:n(f.interestRate)||8.5,tenureYears:n(f.tenureYears)||20,monthlyRent:n(input.user.currentRent),years:n(input.rental.holdingYears)||5});
 const affordabilityFit=clamp(100-risk.pillars.affordability.normalizedPercentage),riskSafety=100-risk.overall.score,financeFit=isCash?80:clamp(100-risk.pillars.debt.normalizedPercentage),costFit=cost.listingPrice?clamp(100-(cost.expected-cost.listingPrice)/cost.listingPrice*400):50,rentalFit=rental?clamp(rental.healthScore):null,buyFit=buyVsRent.monthlyDifference<=0?75:clamp(70-buyVsRent.monthlyDifference/Math.max(totalIncome,1)*100); const drivers=[['Affordability',affordabilityFit,30],['Risk safety',riskSafety,25],['Financing',financeFit,15],['True cost',costFit,10],['Buy vs rent',buyFit,10],...(rentalFit!==null?[['Rental ROI',rentalFit,10]]:[])]; const weight=drivers.reduce((a,[,,w])=>a+w,0);let fit=Math.round(drivers.reduce((a,[,score,w])=>a+score*w,0)/weight);
 if(risk.metrics.monthlyBalance<0||risk.overall.score>80||risk.metrics.emergencyBufferMonths<1||cost.expected>risk.metrics.stretchMaximum&&risk.metrics.stretchMaximum>0)fit=Math.min(fit,49); else if(risk.overall.score>65||cost.expected>risk.metrics.comfortableMaximum&&risk.metrics.comfortableMaximum>0)fit=Math.min(fit,64);
 const reasons=[],strengths=[],concerns=[]; const add=(ok,text)=>{(ok?strengths:concerns).push(text);reasons.push({positive:ok,text})}; add(risk.metrics.emergencyBufferMonths>=6,`Emergency reserve covers ${risk.metrics.emergencyBufferMonths.toFixed(1)} months of essentials.`);add(risk.metrics.monthlyBalance>=0,`Monthly ${risk.metrics.monthlyBalance>=0?'surplus':'deficit'} is ₹${Math.round(Math.abs(risk.metrics.monthlyBalance)).toLocaleString('en-IN')}.`);add(risk.metrics.affordabilityGap<=0, risk.metrics.affordabilityGap<=0?'Property is within the calculated comfortable range.':`True cost is ₹${Math.round(risk.metrics.affordabilityGap).toLocaleString('en-IN')} above the comfortable range.`);if(rental)add(rental.monthlyCashFlow>=0,`Rental cash flow is ₹${Math.round(Math.abs(rental.monthlyCashFlow)).toLocaleString('en-IN')} per month after expenses and EMI.`);
 const confidence=[input.property.price,input.user.monthlyIncome,input.user.monthlyExpenses,input.user.savings,input.user.emergencyReserve].filter(v=>n(v)>0).length*12+(cost.usesProvidedCost?15:0)+(f.mode!=='UNDECIDED'?15:0)+(input.intent.type==='INVESTMENT'&&n(input.property.expectedRent)>0?10:0);
 let result={input,trueCost:cost,emi:{...emi,loanAmount},affordability,risk,rentalROI:rental,buyVsRent,recommendation:{fitScore:fit,label:label(fit),drivers:drivers.map(([name,score,weight])=>({name,score:Math.round(score),points:Math.round((score/100)*weight-weight)})),strengths:strengths.slice(0,3),concerns:concerns.slice(0,3),reasons},confidence:clamp(confidence),sensitivity:[]};
 if(depth===0){const variants=[];if(!isCash&&loanAmount)variants.push(['Interest +1%',{...input,financing:{...f,interestRate:(n(f.interestRate)||8.5)+1}}]);if(n(input.property.price)>500000)variants.push(['Property price −₹5L',{...input,property:{...input.property,price:Math.max(0,n(input.property.price)-500000),trueCost:Math.max(0,n(input.property.trueCost)-500000)}}]);if(n(input.user.existingEmi)>5000)variants.push(['Existing EMI −₹5K',{...input,user:{...input.user,existingEmi:n(input.user.existingEmi)-5000}}]);result.sensitivity=variants.map(([name,next])=>({name,fitScore:decision(next,1).recommendation.fitScore}));}
 return result;
}
export const analyzeProperty=input=>decision(input);
